### ISSUE TITLE
image dimension calculate to 0

### ISSUE THREAD

**Issue by radin-reth** [levymetal/jquery-resize-image-to-parent#4]
Hi levymetal!

jquery-resize-image-to-parent does not works pretty well after I decide to use it with https://github.com/OwlFonk/OwlCarousel that cause images sometimes visible and sometimes invisible ( width: 0px, height: 0px ). or I need to refresh it sometimes

any help, thanks

**Comment by levymetal** [comment]
jQuery cannot get the size of elements that are hidden. There are three options available to you:

1. Find out if OwlCarousel provides a hook that would allow you to call `.resizeToParent()` when the slide changes to from invisible to visible
2. Instead of using `img` tags, use a `background-image` on each `.item` element, then use `background-size: cover`
3. Find or build a carousel that doesn't use `display: none`.

This is not an issue with the resizeToParent plugin, so I am closing the thread.
